{% set version = "1.0.8" %}
{% set sha256 = "94c7b68d86ad2a9613b4dcffe7bbeb03523d63b5b37918bdf2e4ef34195c1e6c" %}

package:
  name: fribidi
  version:  {{ version }}

source:
   url: https://github.com/fribidi/fribidi/releases/download/v{{ version }}/fribidi-{{ version }}.tar.bz2
   sha256: {{ sha256 }}
   patches:
     - meson-rpaths.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('fribidi') }}

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - ninja

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - fribidi -h

about:
  home: https://github.com/fribidi/fribidi
  license: LGPL-2.1
  license_file: COPYING
  summary: The Free Implementation of the Unicode Bidirectional Algorithm.
  description: |
    One of the missing links stopping the penetration of free software in Middle
    East is the lack of support for the Arabic and Hebrew alphabets. In order to
    have proper Arabic and Hebrew support, the bidi algorithm needs to be
    implemented. It is our hope that this library will stimulate more free
    software in the Middle Eastern countries.
  doc_url: https://github.com/fribidi/fribidi
  dev_url: https://github.com/fribidi/fribidi

extra:
  recipe-maintainers:
    - msarahan
    - mariusvniekerk
