{% set version = "1.0.12" %}
{% set sha256 = "0cd233f97fc8c67bb3ac27ce8440def5d3ffacf516765b91c2cc654498293495" %}

package:
  name: fribidi
  version: {{ version }}

source:
  url: https://github.com/fribidi/fribidi/releases/download/v{{ version }}/fribidi-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - meson-rpaths.patch

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('fribidi') }}

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - ninja

test:
  commands:
    - fribidi -h

about:
  home: https://github.com/fribidi/fribidi
  license: LGPL-2.1
  license_file: COPYING
  summary: The Free Implementation of the Unicode Bidirectional Algorithm.
  description: |
    One of the missing links stopping the penetration of free software in Middle
    East is the lack of support for the Arabic and Hebrew alphabets. In order to
    have proper Arabic and Hebrew support, the bidi algorithm needs to be
    implemented. It is our hope that this library will stimulate more free
    software in the Middle Eastern countries.
  doc_url: https://github.com/fribidi/fribidi
  dev_url: https://github.com/fribidi/fribidi

extra:
  recipe-maintainers:
    - msarahan
    - mariusvniekerk
