# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LkEXgslKEKhBm5t+wtM0BuO73nYdl4GbuS/W7jXWr9NF8wi5HHL2k5jOPrLsn+LZTg9DiB6Eu1uLWMa8WGtlWzCaX9hTOw2dI85CShEMguvkFupeftgwbuBtW1eXSo01eb2p5DbOXTel9oX/AuzF44b1wUo3jH66ktH4+HcVJFg0oSkJUapsDgpQWmu2HxBWs6wl7DcNKRGj7lGuWiR5zGAKmTglw7EzlE3RzhKBajreFc10PaL4g2OYCAcRN3Ci+8x1IfjfArgu4nKrcvzht7wT3dA5IU89e3YJBkq452FW/JsHeSHXiCP+m/JNdaQg0mrVn4s4qDFP5jYhtJ0GqFGbakx5N2R86cgX8R80Y43rpJy7SVxZX7pSIXkQm4Tod3q07cf/JX1bLncA1Xhq3q8cFrTioWTZb+pO66B1yqkyNH/JaDCHLCuYGPhQUeFNwfblceOmiNzVWICDbB/OudrS0zsXCZM0GiOgm5XxVYIlzfQMmXNrxm2IqWrbZ0Zq8FvudU+PgAi6FjxCOZkR/XOWG+Gz6ylw9F/9NLVCyIn8LD8RdecvcNUiQag2qzTNVRmyIbml+C3osuc6zXM34qpiAcferyUhev8BaR+YkAn6RJBAU8m+pVHQPR05sKm6fD+esUtn8vPhrPDyAsFKbTy2MEX9QDNJXeRDyaVnoQ0="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_ UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux-ppc64le

script:
  - export CI=travis


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.travis/run_docker_build.sh; fi